stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./docker-build.sh

deploy_sharing:
  stage: deploy
  variables:
    COMPOSE_PROJECT_NAME: "flow-sharing"
    NGINX_PORT: "81"
  script:
    - echo "COMPOSE_PROJECT_NAME - " $COMPOSE_PROJECT_NAME
    - docker-compose stop
    - docker-compose up -d && sleep 60
    - >
      (echo Instance: ${COMPOSE_PROJECT_NAME} && docker-compose ps 2>&1 ) |
      curl https://api.telegram.org/bot163428577:AAGRz5dCZzlXtXGJxmGWN4Sh8VxO1ncpop4/sendMessage 
      -d chat_id="26075382" --data-urlencode text@-
  tags:
    - dev
  only:
    - sharing


deploy_sms:
  stage: deploy
  variables:
    COMPOSE_PROJECT_NAME: "flow-sms"
    NGINX_PORT: "82"
  script:
    - echo "COMPOSE_PROJECT_NAME - " $COMPOSE_PROJECT_NAME
    - docker-compose stop
    - docker-compose up -d && sleep 60
    - >
      (echo Instance: ${COMPOSE_PROJECT_NAME} && docker-compose ps 2>&1 ) |
      curl https://api.telegram.org/bot163428577:AAGRz5dCZzlXtXGJxmGWN4Sh8VxO1ncpop4/sendMessage 
      -d chat_id="26075382" --data-urlencode text@-
  tags:
    - dev
  only:
    - sms