version: '2.2'
services:
  camunda:
    build: 
      context: .
      dockerfile: etc/Dockerfile-spring
      args:
        jar_file: ./kcell-process-app/build/libs/kcell-process-app.jar
    environment:
      - MAIL_MESSAGE_BASEURL
  camundadb:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=process-engine
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - ./camundadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: "pg_isready --host=camundadb"
      interval: 2s
      timeout: 10s
      retries: 30
  assets:
    build:
      context: .
      dockerfile: etc/Dockerfile-spring
      args:
        jar_file: ./asset-management/build/libs/asset-management.jar
  assetsdb:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=assets
      - POSTGRES_USER=assets
      - POSTGRES_PASSWORD=assets
    healthcheck:
      test: "pg_isready --host=assetsdb"
      interval: 2s
      timeout: 10s
      retries: 30
  directories:
    build:
      context: .
      dockerfile: etc/Dockerfile-spring
      args:
        jar_file: ./directory-management/build/libs/directory-management.jar
  networkinfrastructuredb:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=networkinfrastructure
      - POSTGRES_USER=networkinfrastructure
      - POSTGRES_PASSWORD=networkinfrastructure
    healthcheck:
      test: "pg_isready --host=networkinfrastructuredb"
      interval: 2s
      timeout: 10s
      retries: 30
  nginx:
    image: nginx:1.14.0
    ports:
      - "127.0.0.1:${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html/:/usr/share/nginx/html/:ro
      - ./kcell-process-app/src/main/resources/static/:/usr/share/nginx/kcell/webapp/:ro
      - ./kcell-tasklist-ui/:/usr/share/nginx/kcell-tasklist-ui/:ro
  mail:
    image: tozd/postfix
    volumes:
      - ./mail/run.initialization:/etc/service/postfix/run.initialization:ro
    environment:
      - RELAY_HOST=maildev
      - RELAY_PORT=1025
  maildev:
    image: djfarrelly/maildev
    command: ["bin/maildev", "--base-pathname", "/mail"]
  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /export
