version: '2.2'
services:
  camundadb:
    extends:
      file: common-services.yml
      service: camundadb
    ports:
      - "5432:5432"
  assets:
    extends:
      file: common-services.yml
      service: assets
    depends_on:
      assetsdb:
        condition: service_healthy
  assetsdb:
    extends:
      file: common-services.yml
      service: assetsdb
    ports:
      - "5433:5432"
  directories:
    extends:
      file: common-services.yml
      service: directories
    depends_on:
      networkinfrastructuredb:
        condition: service_healthy
  networkinfrastructuredb:
    extends:
      file: common-services.yml
      service: networkinfrastructuredb  
    ports:
      - "5434:5432"
  nginx:
    extends:
      file: common-services.yml
      service: nginx
    depends_on:
      minio:
        condition: service_healthy
    links:
      - directories
      - assets
      - maildev
    extra_hosts:
      - "camunda:172.18.0.1"
  mail:
    extends:
      file: common-services.yml
      service: mail
    links:
      - maildev
    ports:
      - "1025:25"
  maildev:
    extends:
      file: common-services.yml
      service: maildev
  minio:
    extends:
      file: common-services.yml
      service: minio
    ports:
      - "9000:9000"
