version: '2'
services:
  camunda:
    build: ./kcell-camunda
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - DB_DRIVER=postgresql
      - DB_URL=jdbc:postgresql://db:5432/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
    volumes:
      - ./kcell-demo-process-app/target/kcell-demo-process-app-0.0.1-SNAPSHOT.war:/camunda/standalone/deployments/kcell-demo-process-app.war:ro
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=process-engine
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data:rw
