version: '2.2'
services:
  camunda:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,fluentd
      - FLUENTD_HOST=${FLUENTD_ADDRESS}
      - FLUENTD_TAG=${COMPOSE_PROJECT_NAME}
  camundadb:
    labels:
      - app=camundadb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
  assets:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,fluentd
      - FLUENTD_HOST=${FLUENTD_ADDRESS}
      - FLUENTD_TAG=${COMPOSE_PROJECT_NAME}
  assetsdb:
    labels:
      - app=assetsdb
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
  nginx:
    labels:
      - app=nginx
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
  mail:
    labels:
      - app=mail
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
  minio:
    labels:
      - app=minio
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
  maildev:
    labels:
      - app=maildev
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${COMPOSE_PROJECT_NAME}
        labels: app
