version: '2.2'
services:
  camunda:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,fluentd
      - FLUENTD_HOST=${FLUENTD_ADDRESS}
      - FLUENTD_TAG
  camundadb:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
  assets:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,fluentd
      - FLUENTD_HOST=${FLUENTD_ADDRESS}
      - FLUENTD_TAG
  assetsdb:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
  nginx:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
  mail:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
  minio:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
  maildev:
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
