version: '3'

services:

  camundadb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=process-engine
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - ./camundadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  assetsdb:
    image: mdillon/postgis:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=assets
      - POSTGRES_USER=assets
      - POSTGRES_PASSWORD=assets

  directory-managementdb:
    image: mdillon/postgis:9.6
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=networkinfrastructure
      - POSTGRES_USER=networkinfrastructure
      - POSTGRES_PASSWORD=networkinfrastructure

  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    ports:
      - "9002:9002"
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /export --address ":9002"
    dns:
      - "127.0.0.11"
      - "8.8.8.8"

  nginx:
    image: nginx:1.14.0
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html/:/usr/share/nginx/html/:ro
      - ./kcell-process-app/src/main/resources/static/:/usr/share/nginx/kcell/webapp/:ro
      - ./kcell-tasklist-ui/:/usr/share/nginx/kcell-tasklist-ui/:ro
    dns:
      - "127.0.0.11"
      - "8.8.8.8"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mail:
    image: tozd/postfix:ubuntu-trusty
    ports:
      - "25:25"
    volumes:
      - ./mail/run.initialization:/etc/service/postfix/run.initialization:ro
    environment:
      - RELAY_HOST=maildev
      - RELAY_PORT=1025

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    command: ["bin/maildev", "--base-pathname", "/mail"]

  headless_chrome:
    image: kcell/headless_chrome
    ports:
      - "8800:8800"

  process-app:
    image: kcell/process-app
    ports:
      - "8080:8080"
    volumes:
      - ./ipvpn-samba/files001:/files001
    environment:
      - DATASOURCE_URL=jdbc:postgresql://camundadb:5432/process-engine?stringtype=unspecified
      - DATASOURCE_USER=camunda
      - DATASOURCE_PASSWORD=camunda
      - MINIO_URL=http://minio:9002
      - MAIL_HOST=mail
      - MAIL_PORT=25
      - ASSET_URL=https://asset.test-flow.kcell.kz
      - APP_BASE_URL=https://core.test-flow.kcell.kz
#      - ASSET_URL=http://asset-management:8081
      - EMAIL_DO_SEND=true
      - LDAP_ENABLED=false
      - LDAP_PASSWORD=a%3Wxp79G*J?HB8-
      - LDAP_EXT_ENABLED=false
      - LDAP_EXT_PASSWORD=H243c2A9dy2
      - TEST_CONTROLLER_ENABLED=true
      - IP_VPN_SAMBA_URL=smb://ipvpn-samba/files001
      - IPVPN_CONNECT=true
    extra_hosts:
      - "dbm1-scan1:192.168.116.6"
      - "dbm1dbadm02:192.168.117.3"

  asset-management:
    image: kcell/asset-management
    ports:
      - "8081:8081"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://assetsdb:5432/assets?stringtype=unspecified
      - DATASOURCE_USER=assets
      - DATASOURCE_PASSWORD=assets

  directory-management:
    image: kcell/directory-management
    ports:
      - "8082:8082"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://directory-managementdb:5432/networkinfrastructure?stringtype=unspecified
      - DATASOURCE_USER=networkinfrastructure
      - DATASOURCE_PASSWORD=networkinfrastructure

  ipvpn-samba:
    image: dperson/samba
    environment:
      TZ: 'Asia/Almaty'
    ports:
      - "139:139"
      - "445:445"
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - ./ipvpn-samba/files001:/files001
    command: >
      -S -w "WORKGROUP"
      -s "files001;/files001;yes;no;yes;all;none;;files001 folder for vpn-port-process"
      -p
