version: '2.2'
services:
  camunda:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gelf
      - GELF_HOST=${GRAYLOG_HOST}
      - GELF_PORT=${GRAYLOG_PORT:-12201}
      - GELF_TAG=${COMPOSE_PROJECT_NAME}
  camundadb:
    labels:
      - app=camundadb
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
  assets:
    environment:
      - SPRING_PROFILES_ACTIVE=docker,gelf
      - GELF_HOST=${GRAYLOG_HOST}
      - GELF_PORT=${GRAYLOG_PORT:-12201}
      - GELF_TAG=${COMPOSE_PROJECT_NAME}
  assetsdb:
    labels:
      - app=assetsdb
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
  nginx:
    labels:
      - app=nginx
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
  mail:
    labels:
      - app=mail
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
  minio:
    labels:
      - app=minio
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
  maildev:
    labels:
      - app=maildev
    logging:
      driver: gelf
      options:
        gelf-address: udp://${GRAYLOG_HOST}:${GRAYLOG_PORT:-12201}
        tag: "${COMPOSE_PROJECT_NAME}"
        labels: app
