version: '2'
services:
  camunda:
    build: ./kcell-camunda
    links:
      - camundadb
      - mail
    environment:
      - DB_DRIVER=postgresql
      - DB_URL=jdbc:postgresql://camundadb:5432/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - MAIL_CONFIG=file:///camunda/mail-config.properties
    volumes:
      - ./kcell-demo-process-app/target/deployments/:/camunda/standalone/deployments/kcell/:rw
      - ./kcell-camunda/modules/kz/kcell/camunda/authentication/main/:/camunda/modules/kz/kcell/camunda/authentication/main/:ro
      - ./kcell-camunda/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml:/camunda/modules/org/camunda/bpm/wildfly/camunda-wildfly-subsystem/main/module.xml:ro
      # LDAP authenication             
      # - ./kcell-camunda/standalone/configuration/standalone.xml:/camunda/standalone/configuration/standalone.xml:ro
      - ./kcell-camunda/modules/org/camunda/bpm/camunda-engine-plugin-connect/main/module.xml:/camunda/modules/org/camunda/bpm/camunda-engine-plugin-connect/main/module.xml:ro
      - ./kcell-camunda/modules/org/camunda/bpm/extension/camunda-bpm-mail-core/main:/camunda/modules/org/camunda/bpm/extension/camunda-bpm-mail-core/main:ro
      - ./kcell-camunda/mail-config.properties:/camunda/mail-config.properties:ro
    extra_hosts:
      - "assets:192.168.99.1"
      - "ldap.kcell.kz:192.168.99.1"
  camundadb:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=process-engine
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    # volumes:
    #   - ./camundadb/data:/var/lib/postgresql/data:rw
  # assets:
  #   build: ./asset-management
  #   links:
  #     - assetsdb
  #   ports:
  #     - "8080:8080"
  assetsdb:
    image: mdillon/postgis:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=assets
      - POSTGRES_USER=assets
      - POSTGRES_PASSWORD=assets
    # volumes:
    #   - ./assetsdb/data:/var/lib/postgresql/data:rw
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    links:
      - camunda
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html/:/usr/share/nginx/html/:ro
      - ./kcell-demo-process-app/src/main/webapp/:/usr/share/nginx/kcell/webapp/:ro
    extra_hosts:
      - "assets:192.168.99.1"
  # mail:
  #   image: tozd/postfix:latest
  #   volumes:
  #     - ./mail/run.config:/etc/service/postfix/run.config:ro
  #     - ./mail/run.initialization:/etc/service/postfix/run.initialization:ro
  #   extra_hosts:
  #     - "upstream:smtp1.kcell.kz"
  mail:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
