version: '2.2'
services:
#  camunda:
#    environment:
#      - SPRING_PROFILES_ACTIVE="docker,fluentd"
  camundadb:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
#  assets:
#    environment:
#      - SPRING_PROFILES_ACTIVE="docker,fluentd"
  assetsdb:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  nginx:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  mail:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  minio:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  maildev:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
