version: '2.2'
services:
  camundadb:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  assetsdb:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  nginx:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  mail:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  minio:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}
  maildev:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_ADDRESS}:${FLUENTD_PORT:-24224}
        tag: ${FLUENTD_TAG}