version: '2.2'
services:
  camunda:
    command:
      - "--mail.message.baseurl=https://sharing.dev-flow.kcell.kz"
  camundadb:
    ports:
      - "5432:5432"
  assetsdb:
    ports:
      - "5433:5432"
  networkinfrastructuredb:
    ports:
      - "5434:5432"
