version: '2.2'
services:
  camunda:
    command:
      - "--mail.message.baseurl=https://test-flow.kcell.kz"
    entrypoint:
      - "--kcell.ldap.enabled=true"
      - "--kcell.ldap.managerPassword=8mLZ9*#I"
      - "--external.ldap.enabled=true"
      - "--external.ldap.managerPassword=H243c2A9dy2"
  camundadb:
    ports:
      - "5432:5432"
  assetsdb:
    ports:
      - "5433:5432"
  networkinfrastructuredb:
    ports:
      - "5434:5432"