version: '2.2'
services:
  camunda:
    extends:
      file: common-services.yml
      service: camunda
    links:
      - mail
    depends_on:
      camundadb:
        condition: service_healthy
      minio:
        condition: service_healthy
    entrypoint:
      - "java"
      - "-Djava.security.egd=file:/dev/./urandom"
      - "-jar"
      - "/opt/app.jar"
      - "--spring.profiles.include=docker,sftp"
      - "--kcell.ldap.enabled=true"
      - "--kcell.ldap.managerPassword=A8a#98%cXW"
      - "--mail.message.baseurl=https://sharing.test-flow.kcell.kz"
      - "--server.session.cookie.secure=true"
  camundadb:
    ports:
      - "5432:5432"
  assetsdb:
    ports:
      - "5433:5432"
  networkinfrastructuredb:
    ports:
      - "5434:5432"
