version: '2.2'
services:
  camunda:
    command:
      - "java"
      - "-Djava.security.egd=file:/dev/./urandom"
      - "-jar"
      - "/opt/app.jar"
      - "--spring.profiles.include=docker,sftp"
      - "--external.ldap.enabled=true"
      - "--external.ldap.managerPassword=H243c2A9dy2"
      - "--kcell.ldap.enabled=true"
      - "--kcell.ldap.managerPassword=8mLZ9*#I"
      - "--mail.message.baseurl=https://test-flow.kcell.kz"
      - "--server.session.cookie.secure=true"
  camundadb:
    ports:
      - "5432:5432"
  assetsdb:
    ports:
      - "5433:5432"
  networkinfrastructuredb:
    ports:
      - "5434:5432"