INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_optimization',1,'hq_optimization','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_transmission_engineer',1,'hq_transmission_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_transmission_budget',1,'hq_transmission_budget','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_infrastructure',1,'hq_infrastructure','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_operation',1,'hq_operation','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_leasing',1,'hq_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_sap_specialist_optimization',1,'hq_sap_specialist_optimization','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_sap_specialist_transmission',1,'hq_sap_specialist_transmission','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_sap_specialist_infrastructure',1,'hq_sap_specialist_infrastructure','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_sap_specialist_operation',1,'hq_sap_specialist_operation','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_warehouse',1,'hq_warehouse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('hq_permission',1,'hq_permission','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_engineer',1,'alm_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_optimization_head',1,'alm_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_transmission_head',1,'alm_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_infrastructure_head',1,'alm_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_operation_head',1,'alm_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_power_engineer',1,'alm_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_leasing',1,'alm_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('alm_contractor_lse',1,'alm_contractor_lse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_engineer',1,'astana_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_optimization_head',1,'astana_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_transmission_head',1,'astana_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_infrastructure_head',1,'astana_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_operation_head',1,'astana_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_power_engineer',1,'astana_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_leasing',1,'astana_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('astana_contractor_lse',1,'astana_contractor_lse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_engineer',1,'nc_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_optimization_head',1,'nc_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_transmission_head',1,'nc_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_infrastructure_head',1,'nc_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_operation_head',1,'nc_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_power_engineer',1,'nc_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_leasing',1,'nc_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('nc_contractor_lse',1,'nc_contractor_lse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_engineer',1,'east_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_optimization_head',1,'east_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_transmission_head',1,'east_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_infrastructure_head',1,'east_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_operation_head',1,'east_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_power_engineer',1,'east_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_leasing',1,'east_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('east_contractor_lse',1,'east_contractor_lse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_engineer',1,'south_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_optimization_head',1,'south_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_transmission_head',1,'south_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_infrastructure_head',1,'south_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_operation_head',1,'south_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_power_engineer',1,'south_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_leasing',1,'south_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('south_contractor_lse',1,'south_contractor_lse','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_engineer',1,'west_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_optimization_head',1,'west_optimization_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_transmission_head',1,'west_transmission_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_infrastructure_head',1,'west_infrastructure_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_operation_head',1,'west_operation_head','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_power_engineer',1,'west_power_engineer','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_leasing',1,'west_leasing','WORKFLOW');
INSERT INTO public.act_id_group(id_, rev_, name_, type_) VALUES('west_contractor_lse',1,'west_contractor_lse','WORKFLOW');

insert into act_id_membership(group_id_, user_id_) values('hq_optimization','Marina.Paramonova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_optimization','Daniyar.Yespayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_optimization','Vladimir.Grachyov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_optimization','Gulzhan.Imandosova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_engineer','Sergey.Grigor@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_engineer','Galym.Tulenbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_engineer','Nikolay.Ustinov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_budget','Aigerim.Satybekova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_budget','Tatyana.Solovyova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_budget','Bolat.Idirissov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_transmission_budget','Lyudmila.Vilkova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_infrastructure','Andrey.Medvedev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_infrastructure','Sergey.Chumachenko@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_operation','Kairat.Parmanov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_operation','Askar.Bekmurzayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_operation','Temirlan.Kaliyev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_leasing','Sara.Turabayeva@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_leasing','Ainur.Beknazarova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_leasing','Bella.Mamatova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_leasing','Ikhtiyar.Ibrayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_optimization','Gulzhan.Imandosova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_optimization','Ernat.Suleimenov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_optimization','Dana.Sabitova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_transmission','Aigerim.Satybekova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_transmission','Tatyana.Solovyova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_transmission','Bolat.Idirissov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_transmission','Lyudmila.Vilkova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_infrastructure','Aigerim.Segizbayeva@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_infrastructure','Ernat.Suleimenov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_operation','Chingis.Zholdassov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_sap_specialist_operation','Keremet.Ibragimova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_warehouse','Maral.Amantay@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_warehouse','Rinat.Kurbangaliyev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_warehouse','Dauren.Beispaev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Abai.Shapagatin@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Aidos.Kenzhebayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Alibek.Nurkassymov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Anna.Martynova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Arman.Utepov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Makhabbat.Sasanova@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Ruslan.Tubekbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Yerkebulan.Dauletbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Zhandos.Bolatov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Bahytzhan.Sandybayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('hq_permission','Askar.Pernebekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Alexey.Kolyagin@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Anastassiya.Shenojak@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Dmitriy.Saidashev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Lazizbek.Kurbantayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Nurzhan.Kochshigulov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Sergey.Michshenko@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Kanat.Kulmukhambetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Kerey.Zatilda@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Nurlan.Shokparov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Evgeniy.Degtyarev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Maulen.Kempirbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Nurzhan.Mynbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Asset.Rashitov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Vladimir.Yefanov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Aslan.Shalov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Shyngys.Kassabekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Makhambet.Sameke2@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Alexey.Khudaev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Evgeniy.Semenov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Sergey.Chekh@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Sergey.Lee@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Yevgeniy.Elunin@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Yermek.Tanabekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Andrei.Lugovoy@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Alexey.Kolesnikov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_engineer','Kali.Esimbekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_optimization_head','Kerey.Zatilda@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_optimization_head','Kanat.Kulmukhambetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_transmission_head','Maulen.Kempirbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_infrastructure_head','Kali.Esimbekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_infrastructure_head','Maulen.Kempirbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_infrastructure_head','Samat.Akhmetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_infrastructure_head','Zhanat.Seitkanov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_operation_head','Kali.Esimbekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_operation_head','Maulen.Kempirbayev@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_operation_head','Samat.Akhmetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_operation_head','Zhanat.Seitkanov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_power_engineer','Yevgeniy.Elunin@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_power_engineer','Yermek.Tanabekov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_power_engineer','Alexey.Kolesnikov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_power_engineer','Samat.Akhmetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_power_engineer','Zhanat.Seitkanov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_leasing','Maxim.Goikolov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_leasing','Adilet.Baishalov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_leasing','Samat.Akhmetov@kcell.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','rollout-almaty-main@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','rn-rs-almaty@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','nazym.s@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','botagoz.ch@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','anuarbek.m@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','zhandos.k@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','kairat.b@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','gulzhaina.t@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','meirkhan.k@lse.kz');
insert into act_id_membership(group_id_, user_id_) values('alm_contractor_lse','beibit.a@lse.kz');