FROM openjdk:8u151-jdk
ARG jar_file

ADD ${jar_file} /opt/app.jar

EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=docker
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/opt/app.jar"]
