FROM openjdk:8u151-jdk

ARG jar_file

EXPOSE 8080

ENV SPRING_PROFILES_ACTIVE=docker
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/opt/app.jar"]

ADD ${jar_file} /opt/app.jar
