package kz.kcell.flow.repository.dto;

import java.util.Date;

public class FinancialReportDto {

    public String year;
    public String month;
    public String region;
    public String sitename;
    public String number;
    public String to;
    public String reason;
    public String status;
    public Date requestedDate;
    public String requestedBy;
    public Date validityDate;
    public String relatedTo;
    public String project;
    public Date materialListSigningDate;
    public Date acceptByInitiator;
    public Date acceptByWorkMaintenance;
    public Date acceptByWorkPlanning;
    public Date acceptanceDate;
    public String jobDescription;
    public String quantity;
    public String jobReason;
    public String typeOfExpences;
    public String comments;
    public String customerMaterial;
    public String price;
    public String priceTx;
    public String monthlyAct;
    public String jo;
    public String pr;
    public String prTotalValue;
    public String prStatus;
    public Date prApprovalDate;
    public String po;
    public String invoiceNumber;
    public Date invoiceDate;
/*    public String rejectedByRegionHead;
    public String rejectedByRegionHeadCount;
    public String rejectedByPowerEngineerHead;
    public String rejectedByPowerEngineerHeadCount;
    public String rejectedByCenterHead;
    public String rejectedByCenterHeadCount;
    public String rejectedByLeasingGroup;
    public String rejectedByLeasingGroupCount;
    public String materialListRejectedByRegion;
    public String materialListRejectedByRegionCount;
    public String materialListRejectedByCenter;
    public String materialListRejectedByCenterCount;
    public String materialListRejectedByRegionTNU;
    public String materialListRejectedByRegionTNUCount;
    public String materialListRejectedByCenterPO;
    public String materialListRejectedByCenterPOCount;
    public String materialListRejectedByCenterSAO;
    public String materialListRejectedByCenterSAOCount;
    public String materialListRejectedByCenterTNU;
    public String materialListRejectedByCenterTNUCount;
    public String materialListRejectedByCenterSFM;
    public String materialListRejectedByCenterSFMCount;
    public String trRejectedByRegion;
    public String trRejectedByRegionCount;
    public String trRejectedByCenterGroupPO;
    public String trRejectedByCenterGroupPOCount;
    public String trRejectedByCenterGroupSAO;
    public String trRejectedByCenterGroupSAOCount;
    public String trRejectedByCenterGroupTNU;
    public String trRejectedByCenterGroupTNUCount;
    public String trRejectedByCenterGroupSFM;
    public String trRejectedByCenterGroupSFMCount;
    public String acceptanceRejectedByPermitTeam;
    public String acceptanceRejectedByPermitTeamCount;
    public String acceptanceRejectedByInitiator;
    public String acceptanceRejectedByInitiatorCount;
    public String acceptanceRejectedByMaintenanceGroup;
    public String acceptanceRejectedByMaintenanceGroupCount;
    public String acceptanceRejectedByPlanningGroup;
    public String acceptanceRejectedByPlanningGroupCount;
    public String acceptanceRejectedByRegionHead;
    public String acceptanceRejectedByRegionHeadCount;*/
}
