define([
	'./bulksms/infoBulksms',
	'./freephone/infoFreephone',
	'./infoPbx',
	'./PBX/customerInformation',
	'./PBX/technicalSpecifications',
	'./PBX/sipProtocol',
	'./PBX/e1Protocol',
	'./PBX/sipDirectProtocol',
	'./PBX/vpnTunnel',
	'./PBX/pbxRichText',
	'./uatProcess',
//	'./demand/index',
	'./aftersales/infoAftersales',
  	'./aftersalesPBX/index',
	'./revolvingNumbers/index',
//	'./demandProcess',
	'./bulksmsRichText',
	'./aftersales/infoAftersalesSearch',
	'./search/deliveryPortalSearch',
	'./search/rpaSearch'
	'./aftersalesRevolvingNumbers/index',
//	'./search/demandSearch',
	], function(){});