define([
	'./bulksms/infoBulksms',
	'./freephone/infoFreephone',
	'./infoPbx',
	'./PBX/customerInformation',
	'./PBX/technicalSpecifications',
	'./PBX/sipProtocol',
	'./PBX/e1Protocol',
	'./PBX/sipDirectProtocol',
	'./PBX/vpnTunnel',
	'./PBX/pbxRichText',
	'./uatProcess',
//	'./demand/index',
	'./aftersales/infoAftersales',
  	'./aftersalesPBX/index',
	'./revolvingNumbers/index',
//	'./demandProcess',
	'./bulksmsRichText',
	'./aftersales/infoAftersalesSearch',
	'./search/deliveryPortalSearch',
	'./search/rpaSearch',
	'./aftersalesRevolvingNumbers/index',
  	'./fixedInternet/index',
	'./vpnPortProcess/start/organizePort',
	'./vpnPortProcess/start/disbandPort',
	'./vpnPortProcess/start/organizeVpn',
	'./vpnPortProcess/start/disbandVpn',
	'./vpnPortProcess/start/modifyPort',
	'./vpnPortProcess/start/modifyVpn',
	'./vpnPortProcess/approveRequest/approveOrganizePort',
	'./vpnPortProcess/approveRequest/approveOrganizeVpn',
	'./vpnPortProcess/approveRequest/approveDisbandPort',
	'./vpnPortProcess/approveRequest/approveDisbandVpn',
	'./vpnPortProcess/approveRequest/approveModifyPort',
	'./vpnPortProcess/approveRequest/approveModifyVpn',
//	'./search/demandSearch',
	], function(){});