begin;

ALTER TABLE ACT_HI_VARINST ALTER COLUMN TEXT_ TYPE text;
ALTER TABLE ACT_HI_VARINST ALTER COLUMN TEXT2_ TYPE  text;
ALTER TABLE ACT_HI_DETAIL ALTER COLUMN TEXT_ TYPE  text;
ALTER TABLE ACT_HI_DETAIL ALTER COLUMN TEXT2_ TYPE  text;
ALTER TABLE ACT_ RU_VARIABLE ALTER COLUMN TEXT_ TYPE  text;
ALTER TABLE ACT_ RU_VARIABLE ALTER COLUMN TEXT2_ TYPE  text;

commit;
