begin;
--set client_min_messages to ERROR;
--USERS
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('test_flow@kcell.kz', 1, 'Kcell', 'Test', 'test_flow@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aigerim.Segizbayeva@kcell.kz', 1, 'Aigerim', 'Segizbayeva', 'Aigerim.Segizbayeva@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Ainur.Beknazarova@kcell.kz', 1, 'Ainur', 'Beknazarova', 'Ainur.Beknazarova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aleksandr.Kobelev@kcell.kz', 1, 'Aleksandr', 'Kobelev', 'Aleksandr.Kobelev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexander.Shanygin@kcell.kz', 1, 'Alexander', 'Shanygin', 'Alexander.Shanygin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexey.Khudaev@kcell.kz', 1, 'Alexey', 'Khudaev', 'Alexey.Khudaev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexey.Kolesnikov@kcell.kz', 1, 'Alexey', 'Kolesnikov', 'Alexey.Kolesnikov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexey.Kolyagin@kcell.kz', 1, 'Alexey', 'Kolyagin', 'Alexey.Kolyagin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alibek.Nurkassymov@kcell.kz', 1, 'Alibek', 'Nurkassymov', 'Alibek.Nurkassymov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Amanbek.Suimenbayev@kcell.kz', 1, 'Amanbek', 'Suimenbayev', 'Amanbek.Suimenbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Anastassiya.Shenojak@kcell.kz', 1, 'Anastassiya', 'Shenojak', 'Anastassiya.Shenojak@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Andrei.Lugovoy@kcell.kz', 1, 'Andrei', 'Lugovoy', 'Andrei.Lugovoy@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Andrey.Medvedev@kcell.kz', 1, 'Andrey', 'Medvedev', 'Andrey.Medvedev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Anna.Martynova@kcell.kz', 1, 'Anna', 'Martynova', 'Anna.Martynova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Arman.Utepov@kcell.kz', 1, 'Arman', 'Utepov', 'Arman.Utepov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askar.Bekmurzayev@kcell.kz', 1, 'Askar', 'Bekmurzayev', 'Askar.Bekmurzayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askar.Pernebekov@kcell.kz', 1, 'Askar', 'Pernebekov', 'Askar.Pernebekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askhat.Tatepbaev@kcell.kz', 1, 'Askhat', 'Tatepbaev', 'Askhat.Tatepbaev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aslan.Shalov@kcell.kz', 1, 'Aslan', 'Shalov', 'Aslan.Shalov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Asset.Rashitov@kcell.kz', 1, 'Asset', 'Rashitov', 'Asset.Rashitov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Bahytzhan.Sandybayev@kcell.kz', 1, 'Bahytzhan', 'Sandybayev', 'Bahytzhan.Sandybayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Begaly.Kokin@kcell.kz', 1, 'Begaly', 'Kokin', 'Begaly.Kokin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Beibit.Bitenov@kcell.kz', 1, 'Beibit', 'Bitenov', 'Beibit.Bitenov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Bella.Mamatova@kcell.kz', 1, 'Bella', 'Mamatova', 'Bella.Mamatova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Bogembay.Tleuzhanov@kcell.kz', 1, 'Bogembay', 'Tleuzhanov', 'Bogembay.Tleuzhanov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Bolat.Idirissov@kcell.kz', 1, 'Bolat', 'Idirissov', 'Bolat.Idirissov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Daniyar.Uzibayev@kcell.kz', 1, 'Daniyar', 'Uzibayev', 'Daniyar.Uzibayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Daniyar.Yespayev@kcell.kz', 1, 'Daniyar', 'Yespayev', 'Daniyar.Yespayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Dauren.Beispaev@kcell.kz', 1, 'Dauren', 'Beispaev', 'Dauren.Beispaev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Dmitriy.Saidashev@kcell.kz', 1, 'Dmitriy', 'Saidashev', 'Dmitriy.Saidashev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 1, 'Evgeniy', 'Semenov', 'Evgeniy.Semenov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Farida.Jumanazarova@kcell.kz', 1, 'Farida', 'Jumanazarova', 'Farida.Jumanazarova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Galym.Tulenbayev@kcell.kz', 1, 'Galym', 'Tulenbayev', 'Galym.Tulenbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Gaukhar.Kaisarova@kcell.kz', 1, 'Gaukhar', 'Kaisarova', 'Gaukhar.Kaisarova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Gulzhan.Imandosova@kcell.kz', 1, 'Gulzhan', 'Imandosova', 'Gulzhan.Imandosova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kairat.Parmanov@kcell.kz', 1, 'Kairat', 'Parmanov', 'Kairat.Parmanov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kali.Esimbekov@kcell.kz', 1, 'Kali', 'Esimbekov', 'Kali.Esimbekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kanat.Kulmukhambetov@kcell.kz', 1, 'Kanat', 'Kulmukhambetov', 'Kanat.Kulmukhambetov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kerey.Zatilda@kcell.kz', 1, 'Kerey', 'Zatilda', 'Kerey.Zatilda@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kirill.Kassatkin@kcell.kz', 1, 'Kirill', 'Kassatkin', 'Kirill.Kassatkin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kuanysh.Khozhamuratov@kcell.kz', 1, 'Kuanysh', 'Khozhamuratov', 'Kuanysh.Khozhamuratov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kuanysh.Kussainbekov@kcell.kz', 1, 'Kuanysh', 'Kussainbekov', 'Kuanysh.Kussainbekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Lazizbek.Kurbantayev@kcell.kz', 1, 'Lazizbek', 'Kurbantayev', 'Lazizbek.Kurbantayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Leila.Raisova@kcell.kz', 1, 'Leila', 'Raisova', 'Leila.Raisova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Lyudmila.Jabrailova@kcell.kz', 1, 'Lyudmila', 'Jabrailova', 'Lyudmila.Jabrailova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Lyudmila.Vilkova@kcell.kz', 1, 'Lyudmila', 'Vilkova', 'Lyudmila.Vilkova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Makhabbat.Sasanova@kcell.kz', 1, 'Makhabbat', 'Sasanova', 'Makhabbat.Sasanova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Maral.Amantay@kcell.kz', 1, 'Maral', 'Amantay', 'Maral.Amantay@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Marina.Paramonova@kcell.kz', 1, 'Marina', 'Paramonova', 'Marina.Paramonova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 1, 'Maulen', 'Kempirbayev', 'Maulen.Kempirbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Maxim.Goikolov@kcell.kz', 1, 'Maxim', 'Goikolov', 'Maxim.Goikolov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Nurzhan.Kochshigulov@kcell.kz', 1, 'Nurzhan', 'Kochshigulov', 'Nurzhan.Kochshigulov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Nurzhan.Mynbayev@kcell.kz', 1, 'Nurzhan', 'Mynbayev', 'Nurzhan.Mynbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Rinat.Kurbangaliyev@kcell.kz', 1, 'Rinat', 'Kurbangaliyev', 'Rinat.Kurbangaliyev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Ruslan.Tubekbayev@kcell.kz', 1, 'Ruslan', 'Tubekbayev', 'Ruslan.Tubekbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Samat.Akhmetov@kcell.kz', 1, 'Samat', 'Akhmetov', 'Samat.Akhmetov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sara.Turabayeva@kcell.kz', 1, 'Sara', 'Turabayeva', 'Sara.Turabayeva@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('LSE_Revision_Alm', 2, 'LSE_REVISION', 'Alm', '', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Abai.Shapagatin@kcell.kz', 2, 'Abai', 'Shapagatin', 'Abai.Shapagatin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Yernaz.Kalingarayev@kcell.kz', 1, 'Yernaz', 'Kalingarayev', 'Yernaz.Kalingarayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askar.Slambekov@kcell.kz', 1, 'Askar', 'Slambekov', 'Askar.Slambekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Anzor.Israilov@kcell.kz', 1, 'Anzor', 'Israilov', 'Anzor.Israilov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Adilet.Baishalov@kcell.kz', 1, 'Adilet', 'Baishalov', 'Adilet.Baishalov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aidos.Kenzhebayev@kcell.kz', 1, 'Aidos', 'Kenzhebayev', 'Aidos.Kenzhebayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aigerim.Iskakova@kcell.kz', 1, 'Aigerim', 'Iskakova', 'Aigerim.Iskakova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Aigerim.Satybekova@kcell.kz', 1, 'Aigerim', 'Satybekova', 'Aigerim.Satybekova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Margarita.Kim@kcell.kz', 1, 'Margarita', 'Kim', 'Margarita.Kim@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Makhambet.Sameke2@kcell.kz', 1, 'Makhambet', 'Sameke2', 'Makhambet.Sameke2@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Ernat.Suleimenov@kcell.kz', 1, 'Ernat', 'Suleimenov', 'Ernat.Suleimenov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Dana.Sabitova@kcell.kz', 1, 'Dana', 'Sabitova', 'Dana.Sabitova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askhat.Tatepbayev@kcell.kz', 1, 'Askhat', 'Tatepbayev', 'Askhat.Tatepbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Keremet.Ibragimova@kcell.kz', 1, 'Keremet', 'Ibragimova', 'Keremet.Ibragimova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Chingis.Zholdassov@kcell.kz', 1, 'Chingis', 'Zholdassov', 'Chingis.Zholdassov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexandr.Kim@kcell.kz', 1, 'Alexandr', 'Kim', 'Alexandr.Kim@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Kirill.Strashenko@kcell.kz', 1, 'Kirill', 'Strashenko', 'Kirill.Strashenko@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('rollout-almaty-main@lse.kz', 1, 'Rollout', 'Almaty-Main', 'rollout-almaty-main@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('rn-rs-almaty@lse.kz', 1, 'RN', 'RS-Almaty', 'rn-rs-almaty@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('botagoz.ch@lse.kz', 1, 'Botagoz', 'Ch', 'botagoz.ch@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('anuarbek.m@lse.kz', 1, 'Anuarbek', 'M', 'anuarbek.m@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('zhandos.k@lse.kz', 1, 'Zhandos', 'K', 'zhandos.k@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('kairat.b@lse.kz', 1, 'Kairat', 'B', 'kairat.b@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('gulzhaina.t@lse.kz', 1, 'Guzhaina', 'T', 'gulzhaina.t@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('meirkhan.k@lse.kz', 1, 'Meirkhan', 'K', 'meirkhan.k@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('beibit.a@lse.kz', 1, 'Beibit', 'A', 'beibit.a@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Nikolay.Ustinov@kcell.kz', 1, 'Nikolay', 'Ustinov', 'Nikolay.Ustinov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('nazym.s@lse.kz', 2, 'Nazym', 'S', 'nazym.s@lse.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Evgeniy.Degtyarev@kcell.kz', 1, 'Evgeniy', 'Degtyarev', 'Evgeniy.Degtyarev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('demo', 2, 'Demo', 'Demo', 'demo@camunda.org', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Ikhtiyar.Ibrayev@kcell.kz', 1, 'Ikhtiyar', 'Ibrayev', 'Ikhtiyar.Ibrayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Nurlan.Shokparov@kcell.kz', 1, 'Nurlan', 'Shokparov', 'Nurlan.Shokparov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Alexey.Zharskiy@kcell.kz', 1, 'Alexey', 'Zharskiy', 'Alexey.Zharskiy@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Askhat.Kapay@kcell.kz', 1, 'Askhat', 'Kapay', 'Askhat.Kapay@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Georgiy.Kan@kcell.kz', 1, 'Georgiy', 'Kan', 'Georgiy.Kan@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Saule.Beisembekova@kcell.kz', 1, 'Saule', 'Beisembekova', 'Saule.Beisembekova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sergey.Chekh@kcell.kz', 1, 'Sergey', 'Chekh', 'Sergey.Chekh@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sergey.Chumachenko@kcell.kz', 1, 'Sergey', 'Chumachenko', 'Sergey.Chumachenko@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sergey.Grigor@kcell.kz', 1, 'Sergey', 'Grigor', 'Sergey.Grigor@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sergey.Lee@kcell.kz', 1, 'Sergey', 'Lee', 'Sergey.Lee@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Sergey.Michshenko@kcell.kz', 1, 'Sergey', 'Michshenko', 'Sergey.Michshenko@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Shyngys.Kassabekov@kcell.kz', 1, 'Shyngys', 'Kassabekov', 'Shyngys.Kassabekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Tatyana.Solovyova@kcell.kz', 1, 'Tatyana', 'Solovyova', 'Tatyana.Solovyova@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Temirlan.Kaliyev@kcell.kz', 1, 'Temirlan', 'Kaliyev', 'Temirlan.Kaliyev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Valeriy.Pogorelov@kcell.kz', 1, 'Valeriy', 'Pogorelov', 'Valeriy.Pogorelov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Vassiliy.Gopkalo@kcell.kz', 1, 'Vassiliy', 'Gopkalo', 'Vassiliy.Gopkalo@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Vladimir.Grachyov@kcell.kz', 1, 'Vladimir', 'Grachyov', 'Vladimir.Grachyov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Vladimir.Yefanov@kcell.kz', 1, 'Vladimir', 'Yefanov', 'Vladimir.Yefanov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Vladislav.Posashkov@kcell.kz', 1, 'Vladislav', 'Posashkov', 'Vladislav.Posashkov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Yerkebulan.Dauletbayev@kcell.kz', 1, 'Yerkebulan', 'Dauletbayev', 'Yerkebulan.Dauletbayev@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Yermek.Tanabekov@kcell.kz', 1, 'Yermek', 'Tanabekov', 'Yermek.Tanabekov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Yevgeniy.Elunin@kcell.kz', 1, 'Yevgeniy', 'Elunin', 'Yevgeniy.Elunin@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Zhanat.Seitkanov@kcell.kz', 1, 'Zhanat', 'Seitkanov', 'Zhanat.Seitkanov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Zhandos.Bolatov@kcell.kz', 1, 'Zhandos', 'Bolatov', 'Zhandos.Bolatov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);
INSERT INTO act_id_user (id_, rev_, first_, last_, email_, pwd_, picture_id_) VALUES ('Konstantin.Pominov@kcell.kz', 1, 'Konstantin', 'Pominov', 'Konstantin.Pominov@kcell.kz', '{SHA}ieSV55Qc+eQOaYDRSha/AjzNTJE=', NULL);


--GROUPS
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('kcellUsers', 1, 'Kcell Users', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('contractor_users', 1, 'Contractor Users', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('revision_managers', 1, 'Revision Managers', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('revision_audit', 1, 'Revision Audit', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('camunda-admin', 1, 'camunda BPM Administrators', 'SYSTEM');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_optimization', 1, 'hq_optimization', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_transmission_engineer', 1, 'hq_transmission_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_transmission_budget', 1, 'hq_transmission_budget', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_infrastructure', 1, 'hq_infrastructure', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_operation', 1, 'hq_operation', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_leasing', 1, 'hq_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_sap_specialist_optimization', 1, 'hq_sap_specialist_optimization', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_sap_specialist_transmission', 1, 'hq_sap_specialist_transmission', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_sap_specialist_infrastructure', 1, 'hq_sap_specialist_infrastructure', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_sap_specialist_operation', 1, 'hq_sap_specialist_operation', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_warehouse', 1, 'hq_warehouse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('hq_permission', 1, 'hq_permission', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_engineer', 1, 'alm_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_optimization_head', 1, 'alm_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_transmission_head', 1, 'alm_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_infrastructure_head', 1, 'alm_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_operation_head', 1, 'alm_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_power_engineer', 1, 'alm_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_leasing', 1, 'alm_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_contractor_lse', 1, 'alm_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_optimization_planning', 1, 'alm_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_infrastructure_planning', 1, 'alm_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_sao_planning', 1, 'alm_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_optimization_maintanance', 1, 'alm_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_infrastructure_maintanance', 1, 'alm_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('alm_sao_maintanance', 1, 'alm_sao_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_engineer', 1, 'astana_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_optimization_head', 1, 'astana_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_transmission_head', 1, 'astana_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_infrastructure_head', 1, 'astana_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_operation_head', 1, 'astana_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_power_engineer', 1, 'astana_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_leasing', 1, 'astana_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_contractor_lse', 1, 'astana_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_optimization_planning', 1, 'astana_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_infrastructure_planning', 1, 'astana_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_sao_planning', 1, 'astana_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_optimization_maintanance', 1, 'astana_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_infrastructure_maintanance', 1, 'astana_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('astana_sao_maintanance', 1, 'astana_sao_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_engineer', 1, 'nc_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_optimization_head', 1, 'nc_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_transmission_head', 1, 'nc_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_infrastructure_head', 1, 'nc_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_operation_head', 1, 'nc_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_power_engineer', 1, 'nc_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_leasing', 1, 'nc_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_contractor_lse', 1, 'nc_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_optimization_planning', 1, 'nc_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_infrastructure_planning', 1, 'nc_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_sao_planning', 1, 'nc_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_optimization_maintanance', 1, 'nc_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_infrastructure_maintanance', 1, 'nc_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('nc_sao_maintanance', 1, 'nc_sao_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_engineer', 1, 'east_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_optimization_head', 1, 'east_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_transmission_head', 1, 'east_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_infrastructure_head', 1, 'east_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_operation_head', 1, 'east_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_power_engineer', 1, 'east_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_leasing', 1, 'east_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_contractor_lse', 1, 'east_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_optimization_planning', 1, 'east_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_infrastructure_planning', 1, 'east_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_sao_planning', 1, 'east_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_optimization_maintanance', 1, 'east_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_infrastructure_maintanance', 1, 'east_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('east_sao_maintanance', 1, 'east_sao_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_engineer', 1, 'south_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_optimization_head', 1, 'south_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_transmission_head', 1, 'south_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_infrastructure_head', 1, 'south_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_operation_head', 1, 'south_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_power_engineer', 1, 'south_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_leasing', 1, 'south_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_contractor_lse', 1, 'south_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_optimization_planning', 1, 'south_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_infrastructure_planning', 1, 'south_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_sao_planning', 1, 'south_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_optimization_maintanance', 1, 'south_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_infrastructure_maintanance', 1, 'south_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('south_sao_maintanance', 1, 'south_sao_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_engineer', 1, 'west_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_optimization_head', 1, 'west_optimization_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_transmission_head', 1, 'west_transmission_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_infrastructure_head', 1, 'west_infrastructure_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_operation_head', 1, 'west_operation_head', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_power_engineer', 1, 'west_power_engineer', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_leasing', 1, 'west_leasing', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_contractor_lse', 1, 'west_contractor_lse', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_optimization_planning', 1, 'west_optimization_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_infrastructure_planning', 1, 'west_infrastructure_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_sao_planning', 1, 'south_sao_planning', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_optimization_maintanance', 1, 'west_optimization_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_infrastructure_maintanance', 1, 'west_infrastructure_maintanance', 'WORKFLOW');
INSERT INTO act_id_group (id_, rev_, name_, type_) VALUES ('west_sao_maintanance', 1, 'south_sao_maintanance', 'WORKFLOW');


--MEMBERSHIPS
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('demo', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('demo', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('demo', 'revision_managers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('demo', 'revision_audit');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('test_flow@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('test_flow@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('test_flow@kcell.kz', 'revision_managers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('test_flow@kcell.kz', 'revision_audit');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yernaz.Kalingarayev@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yernaz.Kalingarayev@kcell.kz', 'revision_managers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yernaz.Kalingarayev@kcell.kz', 'revision_audit');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Slambekov@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Slambekov@kcell.kz', 'revision_managers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Slambekov@kcell.kz', 'revision_audit');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anzor.Israilov@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yernaz.Kalingarayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Slambekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anzor.Israilov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Abai.Shapagatin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Adilet.Baishalov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aidos.Kenzhebayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Iskakova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Satybekova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Segizbayeva@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ainur.Beknazarova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aleksandr.Kobelev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexander.Shanygin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Khudaev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolesnikov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolyagin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alibek.Nurkassymov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Amanbek.Suimenbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anastassiya.Shenojak@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Andrei.Lugovoy@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Andrey.Medvedev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anna.Martynova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Arman.Utepov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Bekmurzayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Pernebekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askhat.Tatepbaev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aslan.Shalov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Asset.Rashitov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bahytzhan.Sandybayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Begaly.Kokin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Beibit.Bitenov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bella.Mamatova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bogembay.Tleuzhanov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bolat.Idirissov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Daniyar.Uzibayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Daniyar.Yespayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dauren.Beispaev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dmitriy.Saidashev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Farida.Jumanazarova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Galym.Tulenbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Gaukhar.Kaisarova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Georgiy.Kan@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Gulzhan.Imandosova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kairat.Parmanov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kali.Esimbekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kanat.Kulmukhambetov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kerey.Zatilda@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kirill.Kassatkin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kuanysh.Khozhamuratov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kuanysh.Kussainbekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lazizbek.Kurbantayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Leila.Raisova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lyudmila.Jabrailova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lyudmila.Vilkova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Makhabbat.Sasanova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maral.Amantay@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Margarita.Kim@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Marina.Paramonova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maxim.Goikolov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Kochshigulov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Mynbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Rinat.Kurbangaliyev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ruslan.Tubekbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Samat.Akhmetov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sara.Turabayeva@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Saule.Beisembekova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chekh@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chumachenko@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Grigor@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Lee@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Michshenko@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Shyngys.Kassabekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Tatyana.Solovyova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Temirlan.Kaliyev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Valeriy.Pogorelov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vassiliy.Gopkalo@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vladimir.Grachyov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vladimir.Yefanov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vladislav.Posashkov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yerkebulan.Dauletbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yermek.Tanabekov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yevgeniy.Elunin@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhanat.Seitkanov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhandos.Bolatov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Makhambet.Sameke2@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ernat.Suleimenov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dana.Sabitova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askhat.Tatepbayev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Keremet.Ibragimova@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Chingis.Zholdassov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kirill.Strashenko@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexandr.Kim@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexandr.Kim@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Begaly.Kokin@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kirill.Strashenko@kcell.kz', 'camunda-admin');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nikolay.Ustinov@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('anuarbek.m@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('beibit.a@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('botagoz.ch@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('kairat.b@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('gulzhaina.t@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('meirkhan.k@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('nazym.s@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('rn-rs-almaty@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('rollout-almaty-main@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('zhandos.k@lse.kz', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('LSE_Revision_Alm', 'contractor_users');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Degtyarev@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Marina.Paramonova@kcell.kz', 'hq_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Daniyar.Yespayev@kcell.kz', 'hq_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vladimir.Grachyov@kcell.kz', 'hq_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Gulzhan.Imandosova@kcell.kz', 'hq_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Grigor@kcell.kz', 'hq_transmission_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Galym.Tulenbayev@kcell.kz', 'hq_transmission_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nikolay.Ustinov@kcell.kz', 'hq_transmission_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Satybekova@kcell.kz', 'hq_transmission_budget');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Tatyana.Solovyova@kcell.kz', 'hq_transmission_budget');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bolat.Idirissov@kcell.kz', 'hq_transmission_budget');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lyudmila.Vilkova@kcell.kz', 'hq_transmission_budget');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Andrey.Medvedev@kcell.kz', 'hq_infrastructure');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chumachenko@kcell.kz', 'hq_infrastructure');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kairat.Parmanov@kcell.kz', 'hq_operation');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Bekmurzayev@kcell.kz', 'hq_operation');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Temirlan.Kaliyev@kcell.kz', 'hq_operation');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sara.Turabayeva@kcell.kz', 'hq_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ainur.Beknazarova@kcell.kz', 'hq_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bella.Mamatova@kcell.kz', 'hq_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ikhtiyar.Ibrayev@kcell.kz', 'hq_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Gulzhan.Imandosova@kcell.kz', 'hq_sap_specialist_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ernat.Suleimenov@kcell.kz', 'hq_sap_specialist_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dana.Sabitova@kcell.kz', 'hq_sap_specialist_optimization');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Satybekova@kcell.kz', 'hq_sap_specialist_transmission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Tatyana.Solovyova@kcell.kz', 'hq_sap_specialist_transmission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bolat.Idirissov@kcell.kz', 'hq_sap_specialist_transmission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lyudmila.Vilkova@kcell.kz', 'hq_sap_specialist_transmission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aigerim.Segizbayeva@kcell.kz', 'hq_sap_specialist_infrastructure');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ernat.Suleimenov@kcell.kz', 'hq_sap_specialist_infrastructure');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Chingis.Zholdassov@kcell.kz', 'hq_sap_specialist_operation');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Keremet.Ibragimova@kcell.kz', 'hq_sap_specialist_operation');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maral.Amantay@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Rinat.Kurbangaliyev@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dauren.Beispaev@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Abai.Shapagatin@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aidos.Kenzhebayev@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alibek.Nurkassymov@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anna.Martynova@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Arman.Utepov@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Makhabbat.Sasanova@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Ruslan.Tubekbayev@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yerkebulan.Dauletbayev@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhandos.Bolatov@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Bahytzhan.Sandybayev@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askar.Pernebekov@kcell.kz', 'hq_permission');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolyagin@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anastassiya.Shenojak@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dmitriy.Saidashev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lazizbek.Kurbantayev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Kochshigulov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Michshenko@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kanat.Kulmukhambetov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kerey.Zatilda@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurlan.Shokparov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Degtyarev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Mynbayev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Asset.Rashitov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Vladimir.Yefanov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Aslan.Shalov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Shyngys.Kassabekov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Makhambet.Sameke2@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Khudaev@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chekh@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Lee@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yevgeniy.Elunin@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yermek.Tanabekov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Andrei.Lugovoy@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolesnikov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kali.Esimbekov@kcell.kz', 'alm_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kerey.Zatilda@kcell.kz', 'alm_optimization_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kanat.Kulmukhambetov@kcell.kz', 'alm_optimization_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 'alm_transmission_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kali.Esimbekov@kcell.kz', 'alm_infrastructure_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 'alm_infrastructure_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Samat.Akhmetov@kcell.kz', 'alm_infrastructure_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhanat.Seitkanov@kcell.kz', 'alm_infrastructure_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kali.Esimbekov@kcell.kz', 'alm_operation_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maulen.Kempirbayev@kcell.kz', 'alm_operation_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Samat.Akhmetov@kcell.kz', 'alm_operation_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhanat.Seitkanov@kcell.kz', 'alm_operation_head');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yevgeniy.Elunin@kcell.kz', 'alm_power_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yermek.Tanabekov@kcell.kz', 'alm_power_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolesnikov@kcell.kz', 'alm_power_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Samat.Akhmetov@kcell.kz', 'alm_power_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Zhanat.Seitkanov@kcell.kz', 'alm_power_engineer');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Maxim.Goikolov@kcell.kz', 'alm_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Adilet.Baishalov@kcell.kz', 'alm_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Samat.Akhmetov@kcell.kz', 'alm_leasing');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('rollout-almaty-main@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('rn-rs-almaty@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('nazym.s@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('botagoz.ch@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('anuarbek.m@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('zhandos.k@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('kairat.b@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('gulzhaina.t@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('meirkhan.k@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('beibit.a@lse.kz', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('LSE_Revision_Alm', 'alm_contractor_lse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Zharskiy@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Zharskiy@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askhat.Kapay@kcell.kz', 'kcellUsers');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Askhat.Kapay@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Daniyar.Uzibayev@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Kirill.Kassatkin@kcell.kz', 'hq_warehouse');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolyagin@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anastassiya.Shenojak@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dmitriy.Saidashev@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lazizbek.Kurbantayev@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Kochshigulov@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Michshenko@kcell.kz', 'alm_optimization_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolyagin@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Anastassiya.Shenojak@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Dmitriy.Saidashev@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Lazizbek.Kurbantayev@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Nurzhan.Kochshigulov@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Michshenko@kcell.kz', 'alm_sao_planning');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Khudaev@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chekh@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Lee@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Kolesnikov@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Andrei.Lugovoy@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Konstantin.Pominov@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yermek.Tanabekov@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Yevgeniy.Elunin@kcell.kz', 'alm_infrastructure_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Khudaev@kcell.kz', 'alm_optimization_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 'alm_optimization_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chekh@kcell.kz', 'alm_optimization_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Lee@kcell.kz', 'alm_optimization_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Degtyarev@kcell.kz', 'alm_optimization_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Alexey.Khudaev@kcell.kz', 'alm_sao_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Evgeniy.Semenov@kcell.kz', 'alm_sao_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Chekh@kcell.kz', 'alm_sao_maintanance');
INSERT INTO act_id_membership (user_id_, group_id_) VALUES ('Sergey.Lee@kcell.kz', 'alm_sao_maintanance');

--FILTERS
INSERT INTO act_ru_filter (id_, rev_, resource_type_, name_, owner_, query_, properties_) VALUES ('00e50a2b-4f69-11e7-a8c6-0242ac120007', 1, 'Task', 'All Tasks', 'demo', '{}', '{"variables":[{"name":"jrNumber","label":"JR Number"}],"description":"All Tasks - Not recommended to be used in production :)","priority":10}');
INSERT INTO act_ru_filter (id_, rev_, resource_type_, name_, owner_, query_, properties_) VALUES ('00e642ad-4f69-11e7-a8c6-0242ac120007', 1, 'Task', 'My Claimed Tasks', 'kcellUsers', '{"taskAssigneeExpression":"${ currentUser() }"}', '{"variables":[{"name":"jrNumber","label":"JR Number"}],"description":"My Claimed Tasks","priority":-10}');
INSERT INTO act_ru_filter (id_, rev_, resource_type_, name_, owner_, query_, properties_) VALUES ('00e83e80-4f69-11e7-a8c6-0242ac120007', 1, 'Task', 'My Unclaimed Tasks', 'kcellUsers', '{"taskCandidateUserExpression":"${currentUser()}"}', '{"variables":[{"name":"jrNumber","label":"JR Number"}],"description":"My Unclaimed Tasks","priority":-10}');
INSERT INTO act_ru_filter (id_, rev_, resource_type_, name_, owner_, query_, properties_) VALUES ('00e99e13-4f69-11e7-a8c6-0242ac120007', 1, 'Task', 'My Group Tasks', 'kcellUsers', '{"taskCandidateGroupInExpression":"${ currentUserGroups() }"}', '{"variables":[{"name":"jrNumber","label":"JR Number"}],"description":"My Group Tasks","priority":-10}');
INSERT INTO act_ru_filter (id_, rev_, resource_type_, name_, owner_, query_, properties_) VALUES ('00e99e28-4f69-11e7-a8c6-0242ac120007', 1, 'Task', 'Revision Tasks', 'revision_managers', '{"processDefinitionName":"Revision"}', '{"variables":[{"name":"jrNumber","label":"JR Number"}],"description":"Revision Tasks","priority":-10}');

--AUTHORIZATIONS
--FILTER AUTHORIZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00e50a2c-4f69-11e7-a8c6-0242ac120007', 1, 1, NULL, 'demo', 5, '00e50a2b-4f69-11e7-a8c6-0242ac120007', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00e7a23f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 5, '00e642ad-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00e928e2-4f69-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 5, '00e83e80-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00ea3a55-4f69-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 5, '00e99e13-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00fd3a57-4f69-11e7-a8c6-0242ac120007', 1, 1, 'revision_managers', NULL, 5, '00e99e28-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00ff4e71-4f69-11e7-a8c6-0242ac120007', 1, 1, 'revision_audit', NULL, 5, '00e99e28-4f69-11e7-a8c6-0242ac120007', 2);

--REVISION PROCESS AUTOHIRZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ab656542-501a-11e7-a8c4-0242ac120006', 3, 1, 'kcellUsers', NULL, 6, 'Revision', 4674);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc61f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'alm_engineer', NULL, 6, 'Revision', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc62f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'astana_engineer', NULL, 6, 'Revision', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc63f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'nc_engineer', NULL, 6, 'Revision', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc64f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'east_engineer', NULL, 6, 'Revision', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc65f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'south_engineer', NULL, 6, 'Revision', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008bc66f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'west_engineer', NULL, 6, 'Revision', 2147483647);

--PROCESS INSTANCE AUTHORIZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008d9ae1-4f69-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 8, '*', 2147483647);

--APPLICATION AUTHORIZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008a3f7e-4f69-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 0, 'tasklist', 32);

--CAMUNDA-ADMIN AUTHORIZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffb319d0-4f68-11e7-a8c6-0242ac120007', 1, 1, 'kcellUsers', NULL, 2, '*', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffb6ea61-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 0, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffb849f2-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 1, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffb90d43-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 2, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffba1eb4-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 3, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffbb7e45-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 4, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffbcb6c6-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 5, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffbda127-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 6, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffbed9a8-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 7, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc06049-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 8, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc171ba-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 9, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc3467b-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 10, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc5de8c-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 11, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc73e1d-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 12, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffc9d62e-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 13, '*', 2147483647);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffcbaaef-4f68-11e7-a8c6-0242ac120007', 1, 1, 'camunda-admin', NULL, 14, '*', 2147483647);

--USER AUTHORIZATION
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('06e2fd21-6569-11e7-b615-0242ac150007', 1, 1, 'kcellUsers', NULL, 1, '*', 2);


--CONTRACTORS
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'anuarbek.m@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'beibit.a@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'botagoz.ch@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'gulzhaina.t@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'kairat.b@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'LSE_Revision_Alm' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'meirkhan.k@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'nazym.s@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'rn-rs-almaty@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'rollout-almaty-main@lse.kz' and group_id_ = 'kcellUsers';
update act_id_membership set group_id_ = 'contractor_users' where user_id_ = 'zhandos.k@lse.kz' and group_id_ = 'kcellUsers';

INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ab656832-501a-11e7-a8c4-0242ac120006', 3, 1, 'contractor_users', NULL, 6, 'Revision', 4674);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008d9ff1-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 8, '*', 2147483647);

INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00fa443f-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 5, '00e642ad-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00e349e2-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 5, '00e83e80-4f69-11e7-a8c6-0242ac120007', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('00ef5f55-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 5, '00e99e13-4f69-11e7-a8c6-0242ac120007', 2);

INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('37a09efc-6569-11e7-b615-0242ac150007', 1, 1, 'contractor_users', NULL, 1, '*', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('ffb445d0-4f68-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 2, '*', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('008a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 0, 'tasklist', 32);

INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('009a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'anuarbek.m@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('010a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'beibit.a@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('011a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'botagoz.ch@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('012a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'gulzhaina.t@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('013a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'kairat.b@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('014a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'LSE_Revision_Alm', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('015a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'meirkhan.k@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('016a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'nazym.s@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('017a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'rn-rs-almaty@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('018a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'rollout-almaty-main@lse.kz', 2);
INSERT INTO act_ru_authorization (id_, rev_, type_, group_id_, user_id_, resource_type_, resource_id_, perms_) VALUES ('019a7f7c-4f69-11e7-a8c6-0242ac120007', 1, 1, 'contractor_users', NULL, 1, 'zhandos.k@lse.kz', 2);

commit;