define([
    './general',
    './details',
    './targetAudience',
    './functionalRequirements',
    './nonFunctionalRequirements',
    './interfaces',
    './resources',
    './materials',
    './supportiveInputs',
    './businessCase',
    './businessIntelligence',
    './demandDropdown',
    './sddFieldConstructor',
    './sddSections',
    './sddPdf',
    './testCases',
    './uatPdf'
], function(){});
