package kz.kcell.kwms.controller.command;

public enum CommandName {
    ADD_FACILITY,
    INSTALL_NEW_EQUIPMENT,
    CONNECT_EQUIPMENT,
    DISMANTLE_EQUIPMENT,
    REMOVE_CONNECTION,
    MODIFY_FACILITY,
    MODIFY_INSTALLATION,
    MODIFY_CONNECTION,
    MODIFY_POWERSOURCE,
    CREATE_POWERSOURCE,
    REPLACE_EQUIPMENT,
    REPLACE_POWERSOURCE,
    REMOVE_POWERSOURCE,
    CREATE_LOCATION
}
